[package]
name = "tflite"
version = "0.3.1"
authors = ["Boncheol Gu <boncheol.gu@gmail.com>"]

description = "Rust bindings for TensorFlow Lite"
keywords = ["tensorflow", "tflite", "bindings"]
license = "MIT/Apache-2.0"
repository = "https://github.com/boncheolgu/tflite-rs"
readme = "README.md"
edition = "2018"

[dependencies]
cpp = "0.5"
failure = "0.1"
libc = "0.2"
maybe-owned = "0.3"

[build-dependencies]
bindgen = "0.50"
cpp_build = "0.5"
failure = "0.1"
flate2 = "1.0"
tar = "0.4"

[features]
debug_tflite = [] # use "libtensorflow-lite.a" built in debug mode
